### PR TITLE
Display color in terminal correctly.

### PR DESCRIPTION
**Pull request by NanXiao**

### CODE REVIEW

**Comment by NanXiao** [comment]
@bofm,

If don't merge this PR, the output likes this on my system:  

```
# make all
\033[32mInstalling Oracle Database software...\033[0m
```

There is no color. 

Thanks!

Best Regards
Nan Xiao

**Comment by bofm** [comment]
In which terminal and shell are you getting bad output?

**Comment by NanXiao** [comment]
@bofm : The terminal is Cygwin, while shell is `Bash 4.2.46(1)-release`.

**Comment by bofm** [comment]
The code in this PR gives me output like `-e Installing Oracle Database software...` in the following terminals in both bash and zsh:
- Terminal.app on OS X
-  iTerm2 v3 in OS X
- Ubuntu 14.04 default terminal
- Remote bash over SSH with Putty on Windows

**Comment by NanXiao** [comment]
That's the capture of executing in Cygwin:
capture1

**Comment by bofm** [comment]
Update Docker to 1.10.

**Pull request closed without merging**
